# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-14 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20170114_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='answer',
            field=models.CharField(default='answer', max_length=200),
            preserve_default=False,
        ),
    ]
